### ISSUE TITLE
NPM 1.0.2 Package Broken

### ISSUE THREAD

**Issue by pluby** [nolanlawson/vuvuzela#6]
The `package.json` file refers to `index.js` which is missing so you get the error `Error: Cannot find module 'vuvuzela'`. `index.js` is present in version 1.0.1 which works just fine.

**Comment by nolanlawson** [comment]
This is a bug in some versions of npm, due to not understanding `"files": []`. If you update npm this error should go away.

That said, I'll still go ahead and fix this.

**Comment by nolanlawson** [comment]
fixed in vuvuzela@1.0.3
